[project]
name = "virtual-mentor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-cloud-texttospeech>=2.33.0",
    "google-genai>=1.50.0",
    "langgraph>=1.1.10",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "openai-whisper>=20250625",
    "pathlib>=1.0.1",
    "yating-tts-sdk>=0.2.2",
]
